global using Xunit;
global using Moq;
global using MockQueryable.Moq;
global using AirFinder.API.Controllers;
global using Microsoft.AspNetCore.Mvc;
global using static AirFinder.Domain.SeedWork.Notification.NotificationModel;
global using AirFinder.Domain.Common;
global using AirFinder.Domain.SeedWork.Notification;
global using Microsoft.AspNetCore.Http;
global using AirFinder.API.Tests.Configuration;